version: "3.5"

services:
  caddy:
    image: siwecos/caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile:ro
      - caddy_certs:/root/.caddy
      - ./caddy/blockpage.html:/srv/blockpage.html:ro

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      LOGSPOUT: ignore

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELK_VERSION}
    # build:
    #   context: logstash/
    #   args:
    #     ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      LOGSPOUT: ignore

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    # build:
    #   context: kibana/
    #   args:
    #     ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - kibana_data:/usr/share/kibana/data
    environment:
      LOGSPOUT: ignore
    depends_on:
      - elasticsearch

  logspout:
    build:
      context: logspout/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      ROUTE_URIS: logstash+tcp://logstash:5000
      LOGSTASH_TAGS: docker-elk
      LOGSPOUT: ignore
      SYSLOG_FORMAT: rfc3164
    restart: on-failure
    depends_on:
      - logstash

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:${ELK_VERSION}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
      - ./metricbeat/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro
    environment:
      ELASTICSEARCH_HOSTS: elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
      KIBANA_HOST: kibana:5601
      LOGSPOUT: ignore
    restart: on-failure
    network_mode: host
    command:
      - "-system.hostfs=/hostfs"

volumes:
  caddy_certs:
  es_data:
  kibana_data:
