version: '3'

services:

  caddy:
    image: siwecos/caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile:ro
      - caddy_certs:/root/.caddy
      - ./caddy/blockpage.html:/srv/blockpage.html:ro

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    # ports:
      # - "5000:5000"
      # - "9600:9600"
    networks:
      - elk
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    # depends_on:
    #   - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    # ports:
    #   - "5601:5601"
    depends_on:
      - elasticsearch

networks:
  elk:
    name: elk

volumes:
  caddy_certs:
